### ISSUE TITLE
move middleware to the right

### ISSUE THREAD

**Issue by notmyname** [synhershko/swift-middleware-grok#1]
The middleware should be moved to the right side of the pipeline, probably between "cache" and "bulk".

Otherwise, other middleware that changes the client response won't get handled, eg large objects.

**Comment by synhershko** [comment]
What do you mean by that? I'm using it as the right-most middleware, running just after proxy-server. Do you mean I should push it a bit to the left?

**Comment by notmyname** [comment]
bah! I got my right and left mixed up again. Move it to the left is what I mean. ie towards the "front" of the pipeline.
